<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Deterministic>true</Deterministic>
    <LabRuntimePath Condition="'$(LabRuntimePath)' == ''">$(MSBuildThisFileDirectory)lab-runtime\build-24525702</LabRuntimePath>
    <GameRootPath Condition="'$(GameRootPath)' == ''">$(LabRuntimePath)</GameRootPath>
    <GameManagedPath Condition="'$(GameManagedPath)' == ''">$(GameRootPath)\ZumbiBlocks2_Data\Managed</GameManagedPath>
    <BepInExReferencePath Condition="'$(BepInExReferencePath)' == ''">$(LabRuntimePath)\BepInEx\core</BepInExReferencePath>
  </PropertyGroup>
</Project>
