<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Deterministic>true</Deterministic>
    <LabRuntimePath Condition="'$(LabRuntimePath)' == ''">$(MSBuildThisFileDirectory)lab-runtime\build-24525702</LabRuntimePath>
    <GameManagedPath Condition="'$(GameManagedPath)' == ''">$(LabRuntimePath)\ZumbiBlocks2_Data\Managed</GameManagedPath>
  </PropertyGroup>
</Project>

